version: '3.5'
services:
    api:
        image: ranger.services.breadcrumbs:dev
        container_name: breadcrumbs
        ports:
            - '8088:8088'
        networks:
            - breadcrumbs
            - ranger

networks:
    ranger:
        name: ranger-network
        external: true

    breadcrumbs:
        name: breadcrumbs-network
        external: true
